Lab11/Models/StudentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab11.Models
{
    public class StudentModel
    {
        //public int ID { get; set; }
        //public string Name { get; set; }
        //public string LastName { get; set; }
        //public string Address { get; set; }
        //public DateTime CreatedDate { get; set; }
        //public DateTime? UpdatedDate { get; set; }
        public int studentID { get; set; }
        public string studentName { get; set; }
        public string studentAddress { get; set; }
    }
}

Lab11/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab11.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab11/Controllers/StudentController.cs
using Lab11.Models;
//using Lab11_Domain;
//using Lab11_Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab11.Controllers
{
    public class StudentController : Controller
    {
        //private StudentService service = new StudentService();
        //// GET: Student
        //public ActionResult IndexRazor()
        //{
        //    var model = (from c in service.Get()
        //                 select new StudentModel
        //                 {
        //                     ID = c.studentID,
        //                     Name = c.studentName,
        //                     LastName = c.studentLastName,
        //                     Address = c.studentAddress,
        //                     CreatedDate = c.CreatedDate,
        //                     UpdatedDate = c.UpdatedDate
        //                 }).ToList();
        //    return View(model);
        //}

        //public ActionResult Index()
        //{
        //    return View();
        //}

        //public JsonResult GetStudent(string id)
        //{
        //    return Json(service.Get(), JsonRequestBehavior.AllowGet);
        //}

        //[HttpPost]
        //public ActionResult CreateStudent(Student student)
        //{
        //    service.Insert(student);
        //    string message = "SUCCESS";
        //    return Json(new { Message = message, newStudent = student, JsonRequestBehavior.AllowGet});
        //}

        Proxy.StudentProxy proxy = new Proxy.StudentProxy();

        public ActionResult IndexRazor()
        {
            var response = Task.Run(() => proxy.GetStudentAsync());
            return View(response.Result.listado);
        }

        public JsonResult GetStudent(string id)
        {
            var response = Task.Run(() => proxy.GetStudentAsync());
            return Json(response.Result.listado, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CreateStudent(StudentModel std)
        {
            var response = Task.Run(() => proxy.InsertAsync(std));
            string message = response.Result.Mensaje;
            return Json(new { Message = message, JsonRequestBehavior.AllowGet });
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Lab11/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab11/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab11/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lab11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lab11/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Please enter the details below</h3>
        </div>
        <div class="panel-body">
            <div class="form-group col-md-5">
                <label>Student Name</label>
                <input type="text" name="StudentName" id="StudentName" class="form-control" placeholder="Enter Student Name" value="" />
            </div>
            <div class="form-group col-md-5">
                <label>Student Address</label>
                <input type="text" name="StudentAddress" id="StudentAddress" class="form-control" placeholder="Enter Student Address" value="" />
            </div>
            <div class="form-group col-md-1">
                <div style="float:right; display:inline-block;">
                    <input type="button" name="submitButton" value="Save" id="btnSave" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div> <hr />
    <table id="tblStudent" class="table table-bordered table-striped table-responsive table-hover">
        <thead>
            <tr>
                <th align="left" class="productth">ID</th>
                <th align="left" class="productth">Student Name</th>
                <th align="left" class="productth">Student Address</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {

            LoadData();

            $("#btnSave").click(function () {
                var std = {};
                std.studentName = $("#StudentName").val();
                std.studentAddress = $("#StudentAddress").val();
                let data = JSON.stringify({
                    'StudentName': $("#StudentName").val(),
                    'StudentAddress': $("#StudentAddress").val()
                })
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("CreateStudent","Student")',
                    //data: '{std: ' + JSON.stringify(std) + '}',
                    data: data,
                    dataType: 'json',
                    contentType: "application/json; charset-utf-8",
                    success: function () {
                        LoadData();
                    },
                    error: function () {
                        alert("Error while inserting data");
                    }
                });
                return false;
            });
        });

        function LoadData() {
            $("#tblStudent tbody tr").remove();
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudent","Student")',
                dataType: 'json',
                data: { id: '' },
                success: function (data) {
                    var items = '';
                    $.each(data, function (i, item) {
                        var rows = "<tr>"
                            + "<td class='producttd'>" + item.studentID + "</td>"
                            + "<td class='producttd'>" + item.studentName + "</td>"
                            + "<td class='producttd'>" + item.studentAddress + "</td>"
                            + "</tr>";
                        $("#tblStudent tbody").append(rows);
                    });
                },
                error: function (ex) {
                    var r = jQuery.parseJSON(response.responseText);
                    alert("Message: " + r.Message);
                    alert("StackTrace: " + r.StackTrace);
                    alert("ExceptionType: " + r.ExceptionType);
                }
            });
            return false;
        }
    </script>
}

Lab11/Views/Student/IndexRazor.cshtml
@model List<Lab11.Models.StudentModel>

@{
    ViewBag.Title = "IndexRazor";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Please enter the details below</h3>
        </div>
        <div class="panel-body">
            <div class="form-group col-md-5">
                <label>Student Name</label>
                <input type="text" name="StudentName" id="StudentName" class="form-control" placeholder="Enter Student Name" value="" />
            </div>
            <div class="form-group col-md-5">
                <label>Student Name</label>
                <input type="text" name="StudentLastName" id="StudentLastName" class="form-control" placeholder="Enter Student Last Name" value="" />
            </div>
            <div class="form-group col-md-5">
                <label>Student Address</label>
                <input type="text" name="StudentAddress" id="StudentAddress" class="form-control" placeholder="Enter Student Address" value="" />
            </div>
            <div class="form-group col-md-1">
                <div style="float:right; display:inline-block;">
                    <input type="button" name="submitButton" value="Save" id="btnSave" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div> <hr />
    <table id="tblStudent" class="table table-bordered table-striped table-responsive table-hover">
        <thead>
            <tr>
                <th align="left" class="productth">ID</th>
                <th align="left" class="productth">Name</th>
                <th align="left" class="productth">Last Name</th>
                <th align="left" class="productth">Address</th>
                <th align="left" class="productth">Date Created</th>
                <th align="left" class="productth">Date Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model)
            {
            <tr>
                @*<td align="left" class="productth">@student.ID</td>
                <td align="left" class="productth">@student.Name</td>
                <td align="left" class="productth">@student.LastName</td>
                <td align="left" class="productth">@student.Address</td>
                <td align="left" class="productth">@student.CreatedDate</td>*@
                <td align="left" class="productth">@student.studentID</td>
                <td align="left" class="productth">@student.studentName</td>
                <td align="left" class="productth">@student.studentAddress</td>
            </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {

            $("#btnSave").click(function () {
                var std = {};
                std.studentName = $("#StudentName").val();
                std.studentLastName = $("#StudentLastName").val();
                std.studentAddress = $("#StudentAddress").val();
                let data = JSON.stringify({
                    'StudentName': $("#StudentName").val(),
                    'StudentLastName': $("#StudentLastName").val(),
                    'StudentAddress': $("#StudentAddress").val()
                })
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("CreateStudent")',
                    data: data,
                    dataType: 'json',
                    contentType: "application/json; charset-utf-8",
                    success: function (data) {
                        let newStudent = data.newStudent;
                        AddRow(
                            newStudent.studentID,
                            newStudent.studentName,
                            newStudent.studentLastName,
                            newStudent.studentAddress,
                            newStudent.CreatedDate);
                    },
                    error: function () {
                        alert("Error while inserting data");
                    }
                });
                return false;
            });
        });

        function AddRow(id, name, lastName, address, createdDate) {
            var row = "<tr>"
                + "<td class='producttd'>" + id + "</td>"
                + "<td class='producttd'>" + name + "</td>"
                + "<td class='producttd'>" + lastName + "</td>"
                + "<td class='producttd'>" + address + "</td>"
                + "<td class='producttd'>" + createdDate + "</td>"
                + "<td class='producttd'></td>"
                + "</tr>";
             $("#tblStudent tbody").append(row);
        };

                @*function LoadData() {
            $("#tblStudent tbody tr").remove();
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudent")',
                dataType: 'json',
                data: { id: '' },
                success: function (data) {
                    var items = '';
                    $.each(data, function (i, item) {
                        var rows = "<tr>"
                            + "<td class='producttd'>" + item.studentID + "</td>"
                            + "<td class='producttd'>" + item.studentName + "</td>"
                            + "<td class='producttd'>" + item.studentAddress + "</td>"
                            + "</tr>";
                        $("#tblStudent tbody").append(rows);
                    });
                },
                error: function (ex) {
                    var r = jQuery.parseJSON(response.responseText);
                    alert("Message: " + r.Message);
                    alert("StackTrace: " + r.StackTrace);
                    alert("ExceptionType: " + r.ExceptionType);
                }
            });
            return false;
        }*@
    </script>
}